import "./global.css";
import styles from "./app.module.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className={styles.headerFooter}>
          <nav className={styles.navBar}>
            <Link href="/">Home</Link>
            <Link href="/influences">Main influences</Link>
          </nav>
        </header>
        <main>{children}</main>
        <footer className={styles.headerFooter}>[This is a footer]</footer>
      </body>
    </html>
  );
}
